version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install Jest
          command: yarn i jest
      - run:
          name: Install Dependencies
          command: yarn i
      - run:
          name: Run Tests
          command: yarn test
workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              only: master
